# Generated by Django 3.1.6 on 2021-02-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='companys',
            new_name='companies',
        ),
    ]
